// File generated from our OpenAPI spec by Stainless.

package com.dataleonlabs.api.models.individuals

import com.dataleonlabs.api.core.JsonValue
import com.dataleonlabs.api.core.jsonMapper
import com.dataleonlabs.api.models.companies.AmlSuspicion
import com.dataleonlabs.api.models.companies.Certificat
import com.dataleonlabs.api.models.companies.Check
import com.dataleonlabs.api.models.companies.Property
import com.dataleonlabs.api.models.companies.Risk
import com.dataleonlabs.api.models.companies.TechnicalData
import com.dataleonlabs.api.models.companies.documents.GenericDocument
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IndividualTest {

    @Test
    fun create() {
        val individual =
            Individual.builder()
                .id("123e4567-e89b-12d3-a456-426614174000")
                .addAmlSuspicion(
                    AmlSuspicion.builder()
                        .caption("Suspicious activity")
                        .country("FR")
                        .gender("M")
                        .relation("linked")
                        .schema("v1")
                        .score(0.85f)
                        .source("https://aml-checker.example.com/api/v1/suspicion/12345")
                        .status(AmlSuspicion.Status.PENDING)
                        .type(AmlSuspicion.Type.PEP)
                        .build()
                )
                .authUrl("https://id.dataleon.ai/a/123")
                .certificat(
                    Certificat.builder()
                        .id("cert_123")
                        .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .filename("certificate.pdf")
                        .build()
                )
                .addCheck(
                    Check.builder()
                        .masked(false)
                        .message("Name matched successfully")
                        .name("name_match")
                        .validate(true)
                        .weight(1L)
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDocument(
                    GenericDocument.builder()
                        .id("doc_123")
                        .addCheck(
                            Check.builder()
                                .masked(false)
                                .message("Name matched successfully")
                                .name("name_match")
                                .validate(true)
                                .weight(1L)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .documentType("generic")
                        .name("generic_doc")
                        .signedUrl("https://cdn.example.com/doc.pdf")
                        .state("SUBMITTED")
                        .status("approved")
                        .addTable(
                            GenericDocument.Table.builder()
                                .addOperation(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .addValue(
                            GenericDocument.Value.builder()
                                .confidence(0.95)
                                .name("Full Name")
                                .addValue(100L)
                                .addValue(200L)
                                .build()
                        )
                        .build()
                )
                .identityCard(
                    Individual.IdentityCard.builder()
                        .id("doc_001")
                        .backDocumentSignedUrl("https://cdn.example.com/back.jpg")
                        .birthPlace("Paris")
                        .birthday("01/01/1990")
                        .country("FR")
                        .expirationDate("2030-01-01")
                        .firstName("John")
                        .frontDocumentSignedUrl("https://cdn.example.com/front.jpg")
                        .gender("M")
                        .issueDate("2020-01-01")
                        .lastName("Doe")
                        .mrzLine1("P<FRADOE<<JOHN<<<<<<<<<<<<<<<<<<<")
                        .mrzLine2("1234567890FRA9001019M2301012<<<<<<<<<<<<<<04")
                        .mrzLine3(null)
                        .type("passport")
                        .build()
                )
                .number(42L)
                .person(
                    Individual.Person.builder()
                        .birthday("01/01/1990")
                        .email("john.doe@example.com")
                        .faceImageSignedUrl("https://cdn.example.com/face.jpg")
                        .firstName("John")
                        .fullName("John Doe")
                        .gender("M")
                        .lastName("Doe")
                        .maidenName("Smith")
                        .phoneNumber("+33612345678")
                        .build()
                )
                .portalUrl("https://portal.dataleon.ai/w/123")
                .addProperty(
                    Property.builder()
                        .name("property_name")
                        .type("string")
                        .value("property_value")
                        .build()
                )
                .risk(Risk.builder().code("20030").reason("Document mismatch").score(0.92f).build())
                .sourceId("ID54410069066")
                .state("WAITING")
                .status("rejected")
                .addTag(
                    Individual.Tag.builder()
                        .key("tag_name")
                        .private_(false)
                        .type("string")
                        .value("tag_value")
                        .build()
                )
                .technicalData(
                    TechnicalData.builder()
                        .activeAmlSuspicions(false)
                        .apiVersion(2L)
                        .approvedAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .callbackUrl("https://example.com/callback")
                        .callbackUrlNotification("https://example.com/notify")
                        .disableNotification(false)
                        .disableNotificationDate(OffsetDateTime.parse("2025-07-12T13:10:00Z"))
                        .exportType("json")
                        .finishedAt(OffsetDateTime.parse("2025-05-05T13:10:00Z"))
                        .ip("192.168.1.1")
                        .language("fra")
                        .locationIp("203.0.113.45")
                        .needReviewAt(null)
                        .notificationConfirmation(false)
                        .qrCode("false")
                        .rawData(true)
                        .rejectedAt(null)
                        .sessionDuration(45L)
                        .startedAt(OffsetDateTime.parse("2025-05-05T13:00:00Z"))
                        .transferAt(OffsetDateTime.parse("2025-07-12T14:00:00Z"))
                        .transferMode("API")
                        .build()
                )
                .webviewUrl("https://id.dataleon.ai/w/123")
                .workspaceId("wk_123")
                .build()

        assertThat(individual.id()).isEqualTo("123e4567-e89b-12d3-a456-426614174000")
        assertThat(individual.amlSuspicions())
            .containsExactly(
                AmlSuspicion.builder()
                    .caption("Suspicious activity")
                    .country("FR")
                    .gender("M")
                    .relation("linked")
                    .schema("v1")
                    .score(0.85f)
                    .source("https://aml-checker.example.com/api/v1/suspicion/12345")
                    .status(AmlSuspicion.Status.PENDING)
                    .type(AmlSuspicion.Type.PEP)
                    .build()
            )
        assertThat(individual.authUrl()).isEqualTo("https://id.dataleon.ai/a/123")
        assertThat(individual.certificat())
            .isEqualTo(
                Certificat.builder()
                    .id("cert_123")
                    .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                    .filename("certificate.pdf")
                    .build()
            )
        assertThat(individual.checks())
            .containsExactly(
                Check.builder()
                    .masked(false)
                    .message("Name matched successfully")
                    .name("name_match")
                    .validate(true)
                    .weight(1L)
                    .build()
            )
        assertThat(individual.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(individual.documents())
            .containsExactly(
                GenericDocument.builder()
                    .id("doc_123")
                    .addCheck(
                        Check.builder()
                            .masked(false)
                            .message("Name matched successfully")
                            .name("name_match")
                            .validate(true)
                            .weight(1L)
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                    .documentType("generic")
                    .name("generic_doc")
                    .signedUrl("https://cdn.example.com/doc.pdf")
                    .state("SUBMITTED")
                    .status("approved")
                    .addTable(
                        GenericDocument.Table.builder()
                            .addOperation(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .addValue(
                        GenericDocument.Value.builder()
                            .confidence(0.95)
                            .name("Full Name")
                            .addValue(100L)
                            .addValue(200L)
                            .build()
                    )
                    .build()
            )
        assertThat(individual.identityCard())
            .isEqualTo(
                Individual.IdentityCard.builder()
                    .id("doc_001")
                    .backDocumentSignedUrl("https://cdn.example.com/back.jpg")
                    .birthPlace("Paris")
                    .birthday("01/01/1990")
                    .country("FR")
                    .expirationDate("2030-01-01")
                    .firstName("John")
                    .frontDocumentSignedUrl("https://cdn.example.com/front.jpg")
                    .gender("M")
                    .issueDate("2020-01-01")
                    .lastName("Doe")
                    .mrzLine1("P<FRADOE<<JOHN<<<<<<<<<<<<<<<<<<<")
                    .mrzLine2("1234567890FRA9001019M2301012<<<<<<<<<<<<<<04")
                    .mrzLine3(null)
                    .type("passport")
                    .build()
            )
        assertThat(individual.number()).isEqualTo(42L)
        assertThat(individual.person())
            .isEqualTo(
                Individual.Person.builder()
                    .birthday("01/01/1990")
                    .email("john.doe@example.com")
                    .faceImageSignedUrl("https://cdn.example.com/face.jpg")
                    .firstName("John")
                    .fullName("John Doe")
                    .gender("M")
                    .lastName("Doe")
                    .maidenName("Smith")
                    .phoneNumber("+33612345678")
                    .build()
            )
        assertThat(individual.portalUrl()).isEqualTo("https://portal.dataleon.ai/w/123")
        assertThat(individual.properties())
            .containsExactly(
                Property.builder()
                    .name("property_name")
                    .type("string")
                    .value("property_value")
                    .build()
            )
        assertThat(individual.risk())
            .isEqualTo(
                Risk.builder().code("20030").reason("Document mismatch").score(0.92f).build()
            )
        assertThat(individual.sourceId()).isEqualTo("ID54410069066")
        assertThat(individual.state()).isEqualTo("WAITING")
        assertThat(individual.status()).isEqualTo("rejected")
        assertThat(individual.tags())
            .containsExactly(
                Individual.Tag.builder()
                    .key("tag_name")
                    .private_(false)
                    .type("string")
                    .value("tag_value")
                    .build()
            )
        assertThat(individual.technicalData())
            .isEqualTo(
                TechnicalData.builder()
                    .activeAmlSuspicions(false)
                    .apiVersion(2L)
                    .approvedAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                    .callbackUrl("https://example.com/callback")
                    .callbackUrlNotification("https://example.com/notify")
                    .disableNotification(false)
                    .disableNotificationDate(OffsetDateTime.parse("2025-07-12T13:10:00Z"))
                    .exportType("json")
                    .finishedAt(OffsetDateTime.parse("2025-05-05T13:10:00Z"))
                    .ip("192.168.1.1")
                    .language("fra")
                    .locationIp("203.0.113.45")
                    .needReviewAt(null)
                    .notificationConfirmation(false)
                    .qrCode("false")
                    .rawData(true)
                    .rejectedAt(null)
                    .sessionDuration(45L)
                    .startedAt(OffsetDateTime.parse("2025-05-05T13:00:00Z"))
                    .transferAt(OffsetDateTime.parse("2025-07-12T14:00:00Z"))
                    .transferMode("API")
                    .build()
            )
        assertThat(individual.webviewUrl()).isEqualTo("https://id.dataleon.ai/w/123")
        assertThat(individual.workspaceId()).isEqualTo("wk_123")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val individual =
            Individual.builder()
                .id("123e4567-e89b-12d3-a456-426614174000")
                .addAmlSuspicion(
                    AmlSuspicion.builder()
                        .caption("Suspicious activity")
                        .country("FR")
                        .gender("M")
                        .relation("linked")
                        .schema("v1")
                        .score(0.85f)
                        .source("https://aml-checker.example.com/api/v1/suspicion/12345")
                        .status(AmlSuspicion.Status.PENDING)
                        .type(AmlSuspicion.Type.PEP)
                        .build()
                )
                .authUrl("https://id.dataleon.ai/a/123")
                .certificat(
                    Certificat.builder()
                        .id("cert_123")
                        .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .filename("certificate.pdf")
                        .build()
                )
                .addCheck(
                    Check.builder()
                        .masked(false)
                        .message("Name matched successfully")
                        .name("name_match")
                        .validate(true)
                        .weight(1L)
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDocument(
                    GenericDocument.builder()
                        .id("doc_123")
                        .addCheck(
                            Check.builder()
                                .masked(false)
                                .message("Name matched successfully")
                                .name("name_match")
                                .validate(true)
                                .weight(1L)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .documentType("generic")
                        .name("generic_doc")
                        .signedUrl("https://cdn.example.com/doc.pdf")
                        .state("SUBMITTED")
                        .status("approved")
                        .addTable(
                            GenericDocument.Table.builder()
                                .addOperation(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .addValue(
                            GenericDocument.Value.builder()
                                .confidence(0.95)
                                .name("Full Name")
                                .addValue(100L)
                                .addValue(200L)
                                .build()
                        )
                        .build()
                )
                .identityCard(
                    Individual.IdentityCard.builder()
                        .id("doc_001")
                        .backDocumentSignedUrl("https://cdn.example.com/back.jpg")
                        .birthPlace("Paris")
                        .birthday("01/01/1990")
                        .country("FR")
                        .expirationDate("2030-01-01")
                        .firstName("John")
                        .frontDocumentSignedUrl("https://cdn.example.com/front.jpg")
                        .gender("M")
                        .issueDate("2020-01-01")
                        .lastName("Doe")
                        .mrzLine1("P<FRADOE<<JOHN<<<<<<<<<<<<<<<<<<<")
                        .mrzLine2("1234567890FRA9001019M2301012<<<<<<<<<<<<<<04")
                        .mrzLine3(null)
                        .type("passport")
                        .build()
                )
                .number(42L)
                .person(
                    Individual.Person.builder()
                        .birthday("01/01/1990")
                        .email("john.doe@example.com")
                        .faceImageSignedUrl("https://cdn.example.com/face.jpg")
                        .firstName("John")
                        .fullName("John Doe")
                        .gender("M")
                        .lastName("Doe")
                        .maidenName("Smith")
                        .phoneNumber("+33612345678")
                        .build()
                )
                .portalUrl("https://portal.dataleon.ai/w/123")
                .addProperty(
                    Property.builder()
                        .name("property_name")
                        .type("string")
                        .value("property_value")
                        .build()
                )
                .risk(Risk.builder().code("20030").reason("Document mismatch").score(0.92f).build())
                .sourceId("ID54410069066")
                .state("WAITING")
                .status("rejected")
                .addTag(
                    Individual.Tag.builder()
                        .key("tag_name")
                        .private_(false)
                        .type("string")
                        .value("tag_value")
                        .build()
                )
                .technicalData(
                    TechnicalData.builder()
                        .activeAmlSuspicions(false)
                        .apiVersion(2L)
                        .approvedAt(OffsetDateTime.parse("2025-05-01T12:00:00Z"))
                        .callbackUrl("https://example.com/callback")
                        .callbackUrlNotification("https://example.com/notify")
                        .disableNotification(false)
                        .disableNotificationDate(OffsetDateTime.parse("2025-07-12T13:10:00Z"))
                        .exportType("json")
                        .finishedAt(OffsetDateTime.parse("2025-05-05T13:10:00Z"))
                        .ip("192.168.1.1")
                        .language("fra")
                        .locationIp("203.0.113.45")
                        .needReviewAt(null)
                        .notificationConfirmation(false)
                        .qrCode("false")
                        .rawData(true)
                        .rejectedAt(null)
                        .sessionDuration(45L)
                        .startedAt(OffsetDateTime.parse("2025-05-05T13:00:00Z"))
                        .transferAt(OffsetDateTime.parse("2025-07-12T14:00:00Z"))
                        .transferMode("API")
                        .build()
                )
                .webviewUrl("https://id.dataleon.ai/w/123")
                .workspaceId("wk_123")
                .build()

        val roundtrippedIndividual =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(individual),
                jacksonTypeRef<Individual>(),
            )

        assertThat(roundtrippedIndividual).isEqualTo(individual)
    }
}
